INSERT INTO tbl_servicedata(ServiceID, MobilePhone, TownId, UserID, UserName, UserPassword, EmailAddress, FieldValue1, FieldValue2, FieldValue3, FieldValue4, FieldValue5, FieldValue6, FieldValue7, FieldValue8, FieldValue9, FieldValue10, Approved, URLField, URL, RegDate, StartDate, EndDate, visits) VALUES 
(71, '9177818087 ', 'vizagite', 0, 'Ch.V.Ramana', '8c4574f0','ramanasrushti@gmail.com','allి','','you can also call me at 9290427095', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, '0X0', CURDATE(), NULL, NULL, 3)
(51, '9966283672 ', 'vizagite', 0, 'sridhar', '28fb7802', 'sridharkumar777@gmail.com', 'Persuing MCA', '.net,java,etc', 's/o satyam,
old gajuwaka,
visakhapatnam.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, '0X0', CURDATE(), NULL, NULL, 0)
(88, '9908736744 ', 'vizagite', 0, 'murali', '9439d4a0', 'chmkmca@gmail.com', 'm.c.a(68%', 'fresher', '', 'm.c.a(68%', 'near old s.b.i building,munagapaka', '', NULL, NULL, NULL, NULL, 0, NULL, '0X0', CURDATE(, NULL, NULL, 0
(87, '9346288499 ', 'vizagite', 0, 'srinivas', '876f7e6d', 'anakapallisamacharam@gmail.com', 'D.T.P Operator, Helpers', 'Photo digital studio, Ramachandhra theater, anakapalli', '3,000/-', 'photo shop  work', '9A.M To 12 P.M and 1P.M To 9P.M', 'minimum work experiouns 6 months', '', NULL, NULL, NULL, 0, NULL, '0X0', CURDATE(, NULL, NULL, 0
(54, '9296209001 ', 'vizagite', 0, 'laxmikan', '211630b3', 'srikanth_85@yahoo.com', '3 Years in Hardware', 'Hardware, Printer Repairing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, CURDATE(, NULL, NULL, 4
(88, '9391377318 ', 'vizagite', 0, 'K.V. SRINIVASA RAO', 'ef80516e', 'kvsrinivasarao_2006@yahoo.com', 'B.A, PUC (Commerce & Stenography', '7 Years exp. as Clerk-Typing, Computer Operator', 'Expected Salary  9500/-
Expected Salary 3000/- Partime (2 hours only
Sunday &  Holidays Full Time (8 hours', 'typing higher, MS-Office, windows, word, internet, DTP ETC.', 'Devi Nagar, Sarada Nagar,  ANAKAPALLE', 'home typist, Internet online partime services preferred', NULL, NULL, NULL, NULL, 0, NULL, '0X0', CURDATE(, NULL, NULL, 0
(67, '9030194183 ', 'vizagite', 0, 'Sarat Chandra', '66e49267', 'sarat221766@gmail.com', 'DDR2 RAM for my motherboard', '1000 rs', 'I want a second hand DDR2 RAM for my motherboard,if any one willing to sell it,please contact me on 9030194183', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, '0X0', CURDATE(, NULL, NULL, 0
(35, '9030194183 ', 'vizagite', 0, 'Sravanthi', '66e49267', 'sravanthi.bnl@gmail.com', 'B..L.Sravanthi', '5"', 'M.B.B.S(RMC kakinada', 'Studying for APPG2010', 'nil', 'Kapu', '24-01-1984', 'Hastha', 'Nagula', NULL, 0, NULL, '0X0', CURDATE(, NULL, NULL, 0
(52, '9440787787 ', 'vizagite', 0, 'Kiran', 'ecb9b570', 'kiran@myakp.com', '16 years in software development and training.', 'I can teach basics to advanced concepts and make a student industry-ready if the student is found to be interested in software.
', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, '0X0', CURDATE(, NULL, NULL, 1
